Repository adopted-ember-addons/validated-changeset, pull requests merged in 2020-05, with the labels that each got.

#35 Merge sibling keys with `get`
  src/index.ts
  src/utils/is-leaf.ts
  test/index.test.ts
Labels: enhancement

#36 Safe-set with setter
  src/index.ts
  test/index.test.ts
Labels: enhancement

#38 Safe set for set deep
  src/index.ts
  src/utils/set-deep.ts
Labels: enhancement

#39 Merge sibling keys #set
  src/index.ts
  src/utils/is-leaf.ts
  src/utils/is-object.ts
  test/index.test.ts
Labels: enhancement

#43 Bump Typescript 3.9
  package-lock.json
  package.json
  src/utils/index.ts
Labels: enhancement

#42 Validate nested keys with validate/0
  src/index.ts
  src/utils/flatten-validations.ts
  test/index.test.ts
  test/utils/flatten-validations.test.ts
Labels: bug

#45 Implement recursive object tree proxy to properly handle sibling keys
  .eslintrc.js
  src/index.ts
  src/types/index.ts
  src/utils/object-tree-node.ts
  test/index.test.ts
  test/utils/normalize-object.test.ts
  test/utils/object-tree-node.test.ts
  test/utils/set-deep.test.ts
Labels: bug, enhancement

#46 Ember requires us to add ProxyHandler#set
  src/index.ts
  src/types/index.ts
  src/utils/object-tree-node.ts
  test/utils/object-tree-node.test.ts
Labels: enhancement

#52 use isObject
  src/utils/set-deep.ts
Labels: bug

#50 Ensure isPristine after execute
  src/index.ts
  test/index.test.ts
Labels: enhancement

#55 Add user provided changesetKeys to 4th constructor arg to Changeset
  README.md
  src/index.ts
  src/types/index.ts
  src/utils/object-tree-node.ts
  test/index.test.ts
Labels: bug

#57 Get rid of _valueFor
  src/index.ts
  src/types/index.ts
Labels: enhancement

#60 Detect if object has Change in object tree
  src/index.ts
  test/index.test.ts
Labels: bug
